version: '3'

services:

  codellama:
    build: .
    tty: true
    volumes:
      - .:/home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

